package se.jocke.nb.kafka.nodes.root;

/**
 *
 * @author jocke
 */
public class NBKafkaServiceFilterPanel extends javax.swing.JPanel {

  /**
   * Creates new form AddServiceFilterPanel
   */
  public NBKafkaServiceFilterPanel() {
    initComponents();
  }

  public String getFilterName() {
    return nameTextField.getText();
  }

  public String getFilterExpression() {
    return expressionTextField.getText();
  }

  public boolean isFilterReqex() {
    return isRegexCheckBox.getModel().isSelected();
  }


  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
   * this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    nameTextField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    expressionTextField = new javax.swing.JTextField();
    isRegexCheckBox = new javax.swing.JCheckBox();

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NBKafkaServiceFilterPanel.class, "NBKafkaServiceFilterPanel.jLabel1.text")); // NOI18N

    nameTextField.setText(org.openide.util.NbBundle.getMessage(NBKafkaServiceFilterPanel.class, "NBKafkaServiceFilterPanel.nameTextField.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(NBKafkaServiceFilterPanel.class, "NBKafkaServiceFilterPanel.jLabel2.text")); // NOI18N

    expressionTextField.setText(org.openide.util.NbBundle.getMessage(NBKafkaServiceFilterPanel.class, "NBKafkaServiceFilterPanel.expressionTextField.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(isRegexCheckBox, org.openide.util.NbBundle.getMessage(NBKafkaServiceFilterPanel.class, "NBKafkaServiceFilterPanel.isRegexCheckBox.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2)
              .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(nameTextField)
              .addComponent(expressionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(isRegexCheckBox)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(expressionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(isRegexCheckBox)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField expressionTextField;
  private javax.swing.JCheckBox isRegexCheckBox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField nameTextField;
  // End of variables declaration//GEN-END:variables
}
